// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // The generated client uses nodenext-style ".js" relative imports that
    // only resolve once compiled, so seeding runs against the built output.
    seed: "npm run build && node dist/prisma/seed.js",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
