-- Bank transfer verification: the BANK side of a deposit/withdrawal as new
-- COLUMNS on the existing rows (no new table, by decision). Every ALTER is a
-- nullable-or-defaulted column add — metadata-only in Postgres 17, no table
-- rewrite. The three deposits_open_* / withdrawals_open_payout_idx partial
-- indexes hold only rows still waiting for a bank notification, so the
-- matcher's work scales with transfers that happen, never rows that exist.
-- Generated by `prisma migrate diff` against a throwaway database at the
-- previous migration head; the schema.prisma doc comments explain each index.
-- CreateEnum
CREATE TYPE "BankMatchStatus" AS ENUM ('UNVERIFIED', 'MATCHED', 'PENDING_REVIEW', 'SUSPICIOUS');

-- CreateEnum
CREATE TYPE "BankRiskLevel" AS ENUM ('LOW', 'MEDIUM', 'HIGH');

-- AlterTable
ALTER TABLE "deposits" ADD COLUMN     "bankCheckedAt" TIMESTAMP(3),
ADD COLUMN     "declaredTransferAt" TIMESTAMP(3),
ADD COLUMN     "matchStatus" "BankMatchStatus" NOT NULL DEFAULT 'UNVERIFIED',
ADD COLUMN     "receivingAmount" DECIMAL(12,2),
ADD COLUMN     "receivingEventKey" TEXT,
ADD COLUMN     "receivingScreenshotKey" TEXT,
ADD COLUMN     "receivingTransactionAt" TIMESTAMP(3),
ADD COLUMN     "riskLevel" "BankRiskLevel",
ADD COLUMN     "riskReasons" TEXT[] DEFAULT ARRAY[]::TEXT[];

-- AlterTable
ALTER TABLE "withdrawals" ADD COLUMN     "bankCheckedAt" TIMESTAMP(3),
ADD COLUMN     "matchStatus" "BankMatchStatus" NOT NULL DEFAULT 'UNVERIFIED',
ADD COLUMN     "riskLevel" "BankRiskLevel",
ADD COLUMN     "riskReasons" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "transferAmount" DECIMAL(12,2),
ADD COLUMN     "transferEventKey" TEXT,
ADD COLUMN     "transferScreenshotKey" TEXT,
ADD COLUMN     "transferTransactionAt" TIMESTAMP(3);

-- CreateIndex
CREATE UNIQUE INDEX "deposits_receivingEventKey_key" ON "deposits"("receivingEventKey");

-- CreateIndex
CREATE INDEX "deposits_open_match_idx" ON "deposits"("declaredPaymentAccountId", "reference") WHERE (status = 'PENDING'::"DepositStatus" AND "bankCheckedAt" IS NULL);

-- CreateIndex
CREATE INDEX "deposits_open_amount_idx" ON "deposits"("declaredPaymentAccountId", "amount", "createdAt") WHERE (status = 'PENDING'::"DepositStatus" AND "bankCheckedAt" IS NULL);

-- CreateIndex
CREATE INDEX "deposits_open_createdAt_idx" ON "deposits"("createdAt") WHERE (status = 'PENDING'::"DepositStatus" AND "bankCheckedAt" IS NULL);

-- CreateIndex
CREATE INDEX "deposits_userId_createdAt_idx" ON "deposits"("userId", "createdAt");

-- CreateIndex
CREATE INDEX "deposits_matchStatus_createdAt_idx" ON "deposits"("matchStatus", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "withdrawals_transferEventKey_key" ON "withdrawals"("transferEventKey");

-- CreateIndex
CREATE INDEX "withdrawals_transferTransactionCode_idx" ON "withdrawals"("transferTransactionCode");

-- CreateIndex
CREATE INDEX "withdrawals_open_payout_idx" ON "withdrawals"("amount", "approvedAt") WHERE (status = 'APPROVED'::"WithdrawalStatus" AND "bankCheckedAt" IS NULL AND "transferTransactionCode" IS NULL);

-- CreateIndex
-- Added by the Prove phase: the open-set admin filters order the open payout
-- set by createdAt, which withdrawals_open_payout_idx (amount first) cannot
-- serve; EXPLAIN on 50k rows showed a walk of withdrawals_createdAt_idx that
-- discarded thousands of finished rows per page.
CREATE INDEX "withdrawals_open_createdAt_idx" ON "withdrawals"("createdAt") WHERE (status = 'APPROVED'::"WithdrawalStatus" AND "bankCheckedAt" IS NULL AND "transferTransactionCode" IS NULL);

-- CreateIndex
CREATE INDEX "withdrawals_matchStatus_createdAt_idx" ON "withdrawals"("matchStatus", "createdAt");

