export enum Permission {
  MOVIE_CREATE = 'MOVIE_CREATE',
  MOVIE_UPDATE = 'MOVIE_UPDATE',
  MOVIE_DELETE = 'MOVIE_DELETE',
  VIDEO_UPLOAD = 'VIDEO_UPLOAD',
  USER_MANAGE = 'USER_MANAGE',
  FINANCE_VIEW = 'FINANCE_VIEW',
}
